remote_theme: daattali/beautiful-jekyll@3.0.0
title: [Linn Libraries of Oregon]
defaults:
  -
    scope:
      path: ""
    values:
      layout: "page"
      show-avatar: true
plugins:
  - jekyll-remote-theme

avatar: "/assets/images/logo.png"
navbar-links:
  About: "index"
  Books and more: "https://catalog.linnlibraries.org/"
  Research and homework: "research"
  Staff tools:
    - Circulation policies: "staff-tools/circulation-policies"
