remote_theme: daattali/beautiful-jekyll@3.0.0
title: Linn Libraries of Oregon
author: Linn Libraries Consortium
defaults:
  -
    scope:
      path: ""
    values:
      layout: "page"
      show-avatar: true
      css:
        - assets/css/linn.css
plugins:
  - jekyll-remote-theme

avatar: "/assets/images/logo.png"
navbar-links:
  About: "index"
  Books and more: "https://catalog.linnlibraries.org/"
  Research and homework: "research"
  Member libraries: "members"
  Staff tools:
    - Circulation policies: "staff-tools/circulation-policies"
    - Cataloging: "staff-tools/cataloging/index"

navbar-col: "#eff7f7"
navbar-text-col: "#404040"
navbar-border-col: "red"
page-col: "#fcf9f9"
link-col: "teal"
hover-col: "red"
footer-col: "#eff7f7"
footer-text-col: "red"
footer-link-col: "teal"
