version: 2.1
orbs:
  ruby: circleci/ruby@0.1.2 
  browser-tools: circleci/browser-tools@1.0.1

jobs:
  build:
    docker:
      - image: circleci/ruby:2.7.1-buster-node
    environment:
      - JASMINE_BROWSER: firefox
    executor: ruby/default
    steps:
      - checkout
      - run:
          command: gem update bundler
      - run:
          name: Which bundler?
          command: bundle -v
      - ruby/bundle-install
      - browser-tools/install-firefox
      - browser-tools/install-geckodriver
      - run:
          name: Run all the tests
          command: xvfb-run -a bundle exec rake
